homebanking/clientes/urls.py
from django.urls import path

from . import views


app_name = 'clientes'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('ayuda/', views.AyudaView.as_view(), name='ayuda'),
    path('divisas/', views.DivisasView.as_view(), name='divisas'),
]

homebanking/cuentas/urls.py
from django.urls import path

from . import views

app_name = 'cuentas'
urlpatterns = [
    path('', views.CuentaView, name='cuenta'),
    path('actividad/', views.ActividadView, name='actividad'),
    path('perfil/', views.PerfilView.as_view(), name='perfil'),
    path('fondos/', views.FondosView.as_view(), name='fondos'),
    path('transferencias/', views.TransferenciaView, name='transferencia')
]

homebanking/homebanking/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('clientes.urls')),
    path('cuentas/', include('cuentas.urls')),
    path('admin/', admin.site.urls),
    path('registration/', include('registration.urls')),
    path('prestamos/', include('prestamos.urls')),
    path('tarjetas/', include('tarjetas.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api_rest.urls')),
]

homebanking/prestamos/urls.py
from django.urls import path
from . import views

app_name = 'prestamos'
urlpatterns = [
    path('', views.PrestamosForm.as_view(), name='prestamos'),
]

homebanking/registration/urls.py
from django.urls import path

from . import views

app_name = 'registration'
urlpatterns = [
    path('signup/', views.SignUp.as_view() , name='signup'),
    path('cliente/', views.ClienteRegistration.as_view() , name='registroCliente'),
]

homebanking/tarjetas/urls.py
from django.urls import path

from . import views

app_name = 'tarjetas'
urlpatterns = [
    path('', views.TarjetasView.as_view(), name='tarjetas'),
]

homebanking/cuentas/models.py
from asyncio.windows_events import NULL
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class Cliente(models.Model):
    customer_id = models.AutoField(primary_key=True)
    customer_username = models.OneToOneField(
        'auth.User',models.CASCADE, null=True, blank=True)
    customer_name = models.TextField()
    customer_surname = models.TextField()
    customer_dni = models.TextField(db_column='customer_DNI', unique=True)
    dob = models.DateField(blank=True, null=True)
    branch_id = models.IntegerField(null=True, blank=True)

    class Meta:
        managed = True
        db_table = 'cliente'

    def __str__(self):
        nombre = self.customer_name + " " + self.customer_surname
        return nombre


class Movimientos(models.Model):
    movement_id = models.AutoField(primary_key=True, blank=True)
    account_number = models.ForeignKey(Cliente, models.CASCADE,
        default=1)
    amount = models.FloatField(blank=True, null=True)
    reason = models.TextField(blank=True, null=True)
    operation_type = models.TextField(blank=True, null=True)
    status = models.TextField(blank=True, null=True)
    date = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'movimientos'


class TipoCliente(models.Model):
    client_id = models.AutoField(primary_key=True)
    type_client = models.TextField()
    type_savings_usd = models.BooleanField(
        'Caja de ahorro en dolares', default=False)
    type_max_with = models.IntegerField('Retiro diario maximo', null=True)
    type_commissions = models.FloatField(
        'Porcentaje de comision (%)', null=True)
    type_max_cc = models.IntegerField('Tarjetas de credito maximas', null=True)
    type_max_dc = models.IntegerField('Tarjetas de debito maximas', null=True)
    type_max_check = models.IntegerField('Chequeras maximas', null=True)
    type_max_deposit = models.IntegerField(
        'Depositos maximos sin previo aviso', blank=True, null=True)
    type_overdraft = models.FloatField('Descubierto', null=True)
    type_prestamos = models.FloatField('Prestamos pre aprobados', null=True)

    class Meta:
        managed = True
        db_table = 'tipo_cliente'

    def __str__(self):
        return self.type_client


class TipoCuenta(models.Model):
    type_id = models.AutoField(primary_key=True)
    type_name = models.TextField()

    class Meta:
        managed = True
        db_table = 'tipo_cuenta'

    def __str__(self):
        return self.type_name


class Cuenta(models.Model):
    account_id = models.AutoField(primary_key=True)
    customer = models.ForeignKey(Cliente, models.CASCADE)
    balance = models.IntegerField()
    iban = models.TextField()
    account_type = models.ForeignKey(
        TipoCuenta, models.CASCADE)

    class Meta:
        managed = True
        db_table = 'cuenta'

    def __str__(self):
        texto = str(self.account_type) + " de " + str(self.customer)
        return texto


class Empleado(models.Model):
    employee_id = models.AutoField(primary_key=True)
    employee_name = models.TextField()
    employee_surname = models.TextField()
    employee_hire_date = models.TextField()
    employee_dni = models.TextField(db_column='employee_DNI')
    branch_id = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'empleado'


class AuditoriaCuenta(models.Model):
    audit_id = models.AutoField(primary_key=True, blank=True)
    old_id = models.IntegerField(blank=True, null=True)
    new_id = models.IntegerField(blank=True, null=True)
    old_balance = models.IntegerField(blank=True, null=True)
    new_balance = models.IntegerField(blank=True, null=True)
    old_iban = models.TextField(blank=True, null=True)
    new_iban = models.TextField(blank=True, null=True)
    old_type = models.IntegerField(blank=True, null=True)
    new_type = models.IntegerField(blank=True, null=True)
    user_action = models.TextField(blank=True, null=True)
    created_at = models.TextField()

    class Meta:
        managed = True
        db_table = 'auditoria_cuenta'


class DireccionCliente(models.Model):
    address_client_id = models.TextField(primary_key=True, blank=True)
    address_type_client = models.TextField()

    class Meta:
        managed = True
        db_table = 'Direccion_cliente'


class Direccion(models.Model):
    address_id = models.AutoField(primary_key=True, blank=True)
    address_street = models.TextField()
    address_street_number = models.TextField()
    address_city = models.TextField()
    address_country = models.TextField()
    address_type_required = models.ForeignKey(
        'DireccionCliente', models.CASCADE, db_column='address_type_required', blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'Direccion'


class Sucursal(models.Model):
    branch_id = models.AutoField(primary_key=True)
    branch_number = models.BinaryField()
    branch_name = models.TextField()
    branch_address_id = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'sucursal'

homebanking/cuentas/forms.py
from django import forms

# creating a form


class InputForm(forms.Form):
    monto = forms.FloatField()
    destinatario = forms.CharField()
    motivo = forms.CharField()

homebanking/cuentas/views.py
from datetime import date, datetime
from itertools import count
from math import frexp
from sqlite3 import IntegrityError
from unicodedata import name
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import *
from django.shortcuts import render
from .forms import InputForm
from django.contrib.auth.models import User

from cuentas.models import Cliente


def CuentaView(request):
    username = Cliente.objects.all().filter(customer_username=request.user).first()

    transactions = Movimientos.objects.all().filter(
        account_number=username.customer_id).order_by('-date')[:7]
    for texto in Cuenta.objects.all():
        if texto.customer_id == username.customer_id:
            print('yay')
    cash = Cuenta.objects.filter(customer_id=username.customer_id).first()

    return render(request, 'cuentas/cuenta.html',
                  {'transactions': transactions, 'cash': cash})


""" class CuentaView(LoginRequiredMixin, TemplateView):
    template_name = 'cuentas/cuenta.html' """


def ActividadView(request):
    username = Cliente.objects.all().filter(customer_username=request.user).first()

    transactions = Movimientos.objects.all().order_by('-date').filter(
        account_number=username.customer_id)

    return render(request, 'cuentas/actividad.html',
                  {'transactions': transactions})


def TransferenciaView(request):
    context = {}
    context['form'] = InputForm()
    if request.method == 'POST':
        form = InputForm(request.POST)
        
        if form.is_valid():
            monto = form.cleaned_data['monto']
            motivo = form.cleaned_data['motivo']
            is_interno = lambda x: x.count('.ITBANK')==1
            dest = None
            destinatario = form.cleaned_data['destinatario']
            username = Cliente.objects.all().filter(customer_username=request.user).first()
            cash = Cuenta.objects.filter(
                customer_id=username.customer_id).first().balance
            try:
                if is_interno(destinatario):
                    destinatario = destinatario.replace('.ITBANK','')
                    dest = Cliente.objects.all().filter(
                        customer_username=User.objects.all().filter(username=destinatario).first()).first()
                print(cash, monto, float(cash) > float(monto), username, dest)
                if float(cash) > float(monto) and float(monto) > 0:
                    
                    if username != dest: 
                        try:
                            inp = Movimientos(account_number=username, amount=monto, reason=motivo,
                                                status="Enviado", date=datetime.now(), operation_type="Transferencia")
                            sender = Cuenta.objects.filter(
                                    customer_id=username.customer_id).first()
                            sender.balance -= monto
                            if dest:
                                out = Movimientos(account_number=dest, amount=monto, reason=motivo,
                                            status="Recibido", date=datetime.now(), operation_type="Transferencia")
                                
                                
                                reciever = Cuenta.objects.filter(
                                    customer_id=dest).first()
                                reciever.balance += monto
                                out.save()
                                reciever.save()
                            
                            inp.save()
                            sender.save()
                        except:
                            context['error'] = 'La cuenta a la que le queres enviar el dinero no existe'


                    else:
                        context['error'] = 'No podes transferirte a vos mismo'
                        print('err')

                else:
                    print("as")
                    context['error'] = 'No tenes saldo suficiente'
            except IntegrityError:
                context['error'] = f'No existe el usuario {destinatario}'

    return render(request, "cuentas/transferencias.html", context)


class PerfilView(LoginRequiredMixin, TemplateView):
    template_name = 'cuentas/perfil.html'


class FondosView(LoginRequiredMixin, TemplateView):
    template_name = 'cuentas/fondos.html'

homebanking/cuentas/templates/cuentas/actividad.html
{% extends 'cuentas/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'cuentas/css/actividad.css' %}">

<div class="home-content">
    <div class="contenedor-movimientos">
            <div class="movimientos">
                <table>
                    <thead>
                        <tr>
                            <th>Operacion</th>
                            <th>Tipo de Operacion</th>
                            <th>Estado</th>
                            <th>Fecha</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for x in transactions %}
                        <tr>
                            <td>{{x.reason}}</td>
                            <td>{{x.operation_type}}</td>
                            <td>{{x.status}}</td>
                            <td>{{x.date}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
    </div>
</div>
{% endblock %}

homebanking/cuentas/templates/cuentas/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    
    <link rel="stylesheet" href="{% static 'cuentas/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'tarjetas/css/tarjetas.css' %}">
    <link rel="stylesheet" href="{% static 'clientes/css/ayuda.css'%}">
    <link rel="stylesheet" href="{% static 'clientes/css/index.css'%}">
    
    <link href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" rel="stylesheet" />
  </head>
  <body>
    <div class="sidebar">
      <div class="logo-details">
        <i class='bx bxs-bank'></i>
        <img src="{% static 'registration/images/logo_itbank.png' %}" alt="">
      </div>
      <ul class="nav-links">
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'cuentas:cuenta' %}">
            <i class='bx bx-home-alt' ></i>
            <span class="links_name">Inicio</span>
          </a>
        </li>
        <li>
          <a href="{% url 'cuentas:perfil' %}">
            <i class="bx bx-user"></i>
            <span class="links_name">Mi perfil</span>
          </a>
        </li>
        <li>
          <a href="{% url 'cuentas:actividad' %}">
            <i class="bx bx-money"></i>
            <span class="links_name">Actividad</span>
          </a>
        </li>
        <li>
          <a href="{% url 'cuentas:transferencia' %}">
            <i class="bx bx-money"></i>
            <span class="links_name">Transferir Dinero</span>
          </a>
        </li>
        <li>
          <a href="{% url 'prestamos:prestamos' %}">
            <i class="bx bx-money"></i>
            <span class="links_name">Prestamos</span>
          </a>
        </li>
        {%else%}
        <li>
          <a href="{% url 'login' %}">
            <i class="bx bx-log-out"></i>
            <span class="links_name">Iniciar Sesión</span>
          </a>
        </li>
        <li>
          <a href="{% url 'registration:registroCliente' %}">
            <i class="bx bx-log-out"></i>
            <span class="links_name">Registrarse</span>
          </a>
        </li>
        {% endif %}

        <li>
          <a href="{% url 'clientes:divisas' %}">
            <i class='bx bx-dollar-circle' ></i>
            <span class="links_name">Divisas</span>
          </a>
        </li>
        <li>
          <a href="{% url 'clientes:ayuda' %}">
            <i class='bx bx-help-circle' ></i>
            <span class="links_name">Ayuda</span>
          </a>
        </li>
        <li class="log_out">
          {% if user.is_authenticated %}
          <a href="{% url 'logout' %}">
            <i class="bx bx-log-out"></i>
            <span class="links_name">Cerrar Sesión</span>
          </a>
          {%else%}
          <a href="{% url 'clientes:index' %}">
            <i class="bx bx-log-out"></i>
            <span class="links_name">Volver al Inicio</span>
          </a>
          {% endif %}
        </li>
      </ul>
  </div>
  <section class="home-section">
    <nav>
      <div class="sidebar-button">
        <i class="bx bx-menu sidebarBtn"></i>
        <span class="dashboard">Bienvenido, {{user.username}}</span>
      </div>
    </nav>
    {% block content %}
    {% endblock %}

  </section>

  <script src="{% static 'cuentas/js/cuenta.js' %}"></script>
</body>

</html>

homebanking/cuentas/templates/cuentas/cuenta.html
{% extends 'cuentas/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'cuentas/css/cuenta.css' %}">

<div class="home-content">
  <div class="sales-boxes">
    <div class="top-sales-flex">
      <div class="top-sales box">
        <div class="fondos">
          <h2>Dinero Disponible</h2>
          <p class="balance">${{cash.balance}}</p>
        </div>
        <div class="botones">
          <a class="button" href="{% url 'cuentas:perfil' %}">Ingresar dinero</a>
          <a class="button" href="{% url 'cuentas:transferencia' %}">Transferir dinero</a>
        </div>
      </div>
    </div>
    <div class="movimientos">
      <h2>Movimientos</h2>
      <table>
        <thead>
          <tr>
            <th>Monto</th>
            <th>Operacion</th>
            <th>Tipo de Operacion</th>
            <th>Estado</th>
            <th>Fecha</th>
          </tr>
        </thead>
        <tbody>
          {% for x in transactions %}
          <tr>
            <td>{{x.amount}}</td>
            <td>{{x.reason}}</td>
            <td>{{x.operation_type}}</td>
            <td>{{x.status}}</td>
            <td>{{x.date}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <div>
        <a class="button" href="{% url 'cuentas:actividad' %}">Ver más</a>
      </div>
    </div>
  </div>
  <div id="extra-info">
  </div>
</div>
<script src="{% static 'cuentas/js/extraInfo.js' %}"></script>
{% endblock %}

homebanking/cuentas/templates/cuentas/cuentas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp"
      rel="stylesheet">
      <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
      <link rel="stylesheet" href="../../static/cuentas/css/cuenta.css">
</head>
{% load static %}
<link rel="stylesheet" href="{% static 'cuentas/css/cuentas.css' %}">

<body>
    <div class="contenedor">
        <aside>
            <div class="top">
                <figure class="figure-logo">
                    <img src="https://www.itba.edu.ar/intranet/ols/wp-content/uploads/sites/4/2018/08/logo-itba-1080x675.png" alt="">
                    </figure>
                <div class="close" id="close-btn">
                    <span class="material-icons-sharp">close</span>
                </div>
            </div>

            <div class="sidebar">
                <a href="#">
                    <span class="material-icons-sharp">account_balance</span>
                    <h3>Inicio</h3>
                </a>
                <a href="#">
                    <span class="material-icons-sharp">person</span>
                    <h3>Perfil</h3>
                </a>
                <a href="#">
                    <span class="material-icons-sharp">account_balance_wallet</span>
                    <h3>Fondos</h3>
                </a>
                <a href="#">
                    <span class="material-icons-sharp">credit_card</span>
                    <h3>Tarjetas</h3>
                </a>
                <a href="#">
                    <span class="material-icons-sharp">request_quote</span>
                    <h3>Prestamos</h3>
                </a>
                <a href="#">
                    <span class="material-icons-sharp">monetization_on</span>
                    <h3>Divisas</h3>
                </a>
                <a href="#">
                    <span class="material-icons-sharp">help</span>
                    <h3>Ayuda</h3>
                </a>
                <a href="#">
                    <span class="material-icons-sharp">logout</span>
                    <h3>Cerrar Sesión</h3>
                </a>
        </aside>
    <main>
        <div class="profile">
            <div class="profile-photo">
                <img src="https://www.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png" alt="">
            </div>
            <div class="info">
                <p>Bienvenido, <b>Username</b></p>
            </div>
        </div>
        <div class="insights">
            <div class="sales">
                <span></span>
                <div class="middle">
                    <div class="lef">
                        <h3>Dinero disponible</h3>
                        <h3>$25005</h1>
                    </div>
                </div>
            </div>
            <div class="sales">
                <span></span>
                <div class="middle">
                    <div class="lef">
                        <h3>Tarjetas</h3>
                    </div>
                    <div class="card">
                        <div class="card__inner">
                            <div class="front">
                                <div class="row">
                                    <img src="{% static 'cuentas/images/chip.png' %}" class="card__chip" alt="">
                                    <img src="{% static 'registration/images/logo_itbank.png' %}" class="card__logo" alt="">
                                </div>
                                <div class="row card__num">
                                    <p>1234</p>
                                    <p>5678</p>
                                    <p>9876</p>
                                    <p>5000</p>
                                </div>
                                <div class="row card__name">
                                    <p>{{user.username}}</p>
                                    <p> 10/26</p>
                                </div>
                            </div>
                            <div class="back">
                                <div class="barra"></div>
                                <div class="row card__cvv">
                                    <figure>
                                        <img src="{% static 'cuentas/images/pattern.png' %}" class="" alt="">
                                    </figure>
                                    <p>748</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <a href="">Ver todas las tarjetas</a>
                </div>
            </div>
        </div>
        <div class="movimientos">
            <h2>Movimientos</h2>
            <table>
                <thead>
                    <tr>
                        <td></td>
                        <th>Operacion</th>
                        <th>Tipo de Operacion</th>
                        <th>Estado</th>
                        <th>Fecha</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><span class="material-icons-sharp pendiente">shopping_bag</span></td>
                        <td>Pasajes en Aerolineas Argentinas</td>
                        <td>Compra</td>
                        <td>Pendiente</td>
                        <td>/08/2022</td>
                    </tr>
                    <tr>
                        <td><span class="material-icons-sharp devuelto">shopping_bag</span></td>
                        <td>Compra de Prueba en Uber</td>
                        <td>Compra</td>
                        <td>Devuelto</td>
                        <td>/08/2022</td>
                    </tr>
                    <tr>
                        <td><span class="material-icons-sharp pendiente">shopping_bag</span></td>
                        <td>Transferiste a</td>
                        <td>Transferencia</td>
                        <td>Pendiente</td>
                        <td>/08/2022</td>
                    </tr>
                    <tr>
                        <td><span class="material-icons-sharp aprobado">shopping_bag</span></td>
                        <td>Recargaste SUBE</td>
                        <td>Pago de servicio</td>
                        <td>Aprobado</td>
                        <td>/08/2022</td>
                    </tr>
                    <tr>
                        <td><span class="material-icons-sharp aprobado">shopping_bag</span></td>
                        <td>Transferiste a</td>
                        <td>Transferencia</td>
                        <td>Aprobado</td>
                        <td>/08/2022</td>
                    </tr>
                    <tr>
                        <td><span class="material-icons-sharp aprobado">shopping_bag</span></td>
                        <td>Transferiste a</td>
                        <td>Transferencia</td>
                        <td>Aprobado</td>
                        <td>/08/2022</td>
                    </tr>
                    <tr>
                        <td><span class="material-icons-sharp aprobado">shopping_bag</span></td>
                        <td>Pagaste Internet Fibra optica</td>
                        <td>Pago de servicio</td>
                        <td>Aprobado</td>
                        <td>/08/2022</td>
                    </tr>
                    
                </tbody>
            </table>
            <a href="#" class="btn btn-primary">Ver más</a>
        </div>
    </main>

    <div class="right">
        <div class="top">
            <button class="material-icons-sharp">
                menu
            </button>
        </div>
        <div class="ultimas-novedades">
            <div class="novedades">
                <h2>Novedades</h2>
                <div class="novedad">
                    <div class="novedad__img">
                        <img src="" alt="">
                    </div>
                    <div class="mensaje">
                        <p>Su transferencia ha sido enviada con exito</p>
                        <small>Hace 1 hora</small>
                    </div>
                </div>
                <div class="novedad">
                    <div class="novedad__img">
                        <img src="" alt="">
                    </div>
                    <div class="mensaje">
                        <p>Itbank ha lanzado nuevos prestamos</p>
                        <small>Lunes 8 de agosto de 2022</small>
                    </div>
                </div>
                <div class="novedad">
                    <div class="novedad__img">
                        <img src="" alt="">
                    </div>
                    <div class="mensaje">
                        <p>Itbank incluyo una nueva linea de tarjetas llamada black card</p>
                        <small>Jueves 4 de agosto</small>
                    </div>
                </div>
            </div>
        </div>
        <div class="divisas">
            <h2>Divisas</h2>
            <div class="divisa-info">

                <div class="divisa">
                    <img src="" alt="">
                    <h3>Dolar Oficial</h3>
                </div>
                <div class="compra-venta">
                    <p>Compra:<span></span></p>
                    <p>Venta:<span></span></p>
                </div>
                <div class="variacion">
                    <p>Variacion:<span></span></p>
                </div>
            </div>
            <div class="divisa-info">

                <div class="divisa">
                    <img src="" alt="">
                    <h3>Dolar Blue</h3>
                </div>
                <div class="compra-venta">
                    <p>Compra:<span></span></p>
                    <p>Venta:<span></span></p>
                </div>
                <div class="variacion">
                    <p>Variacion:<span></span></p>
                </div>
            </div>
            <div class="divisa-info">
                <div class="divisa">
                    <img src="" alt="">
                    <h3>Dolar Bolsa</h3>
                </div>
                <div class="compra-venta">
                    <p>Compra:<span></span></p>
                    <p>Venta:<span></span></p>
                </div>
                <div class="variacion">
                    <p>Variacion:<span></span></p>
                </div>
            </div>
        </div>
    </div>
    </div>
</body>
</html>

homebanking/cuentas/templates/cuentas/perfil.html
{% extends 'cuentas/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'cuentas/css/perfil.css' %}">

<div class="home-content">
    <section class="contenedor-perfil">
        <div class="contenedor-alias">
            <h2>Perfil</h2>
            <div class="copy-text">
                <div>
                    <small>Alias</small>
                    <input type="text" readonly class="text" value="{{ user.username }}.ITBANK">
                </div>
                <button>
                    <i class='bx bx-copy'></i>
                </button>
            </div>
            <a href="{% url 'tarjetas:tarjetas' %}" class="">
                Tarjetas
                <button>
                    <i class='bx bx-chevron-right'></i>
                </button>
            </a>
            <!-- <a href="#" class="">
                    Direcciones
                    <button>
                        <i class='bx bx-chevron-right'></i>
                    </button>
                </a> -->
        </div>
    </section>
</div>
<script src="{% static 'cuentas/js/perfil.js' %}"></script>
{% endblock %}

homebanking/cuentas/templates/cuentas/transferencias.html
{% extends 'cuentas/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'cuentas/css/transferencias.css'%}">

<div class="home-content">
    <section class="transferencias">
        <div class="contenedor-form">
        <h2>Enviar Dinero</h2>
        <form action="" method="POST">
            {%csrf_token%}
            {{form}}
            <button type="submit" class="btn">Enviar</button>
        </form>
        </div>
    </section>
    </div>
</div>
{% endblock %}