homebanking/clientes/urls.py
from django.urls import path

from . import views


app_name = 'clientes'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('ayuda/', views.AyudaView.as_view(), name='ayuda'),
    path('divisas/', views.DivisasView.as_view(), name='divisas'),
]

homebanking/cuentas/urls.py
from django.urls import path

from . import views

app_name = 'cuentas'
urlpatterns = [
    path('', views.CuentaView, name='cuenta'),
    path('actividad/', views.ActividadView, name='actividad'),
    path('perfil/', views.PerfilView.as_view(), name='perfil'),
    path('fondos/', views.FondosView.as_view(), name='fondos'),
    path('transferencias/', views.TransferenciaView, name='transferencia')
]

homebanking/homebanking/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('clientes.urls')),
    path('cuentas/', include('cuentas.urls')),
    path('admin/', admin.site.urls),
    path('registration/', include('registration.urls')),
    path('prestamos/', include('prestamos.urls')),
    path('tarjetas/', include('tarjetas.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api_rest.urls')),
]

homebanking/registration/urls.py
from django.urls import path

from . import views

app_name = 'registration'
urlpatterns = [
    path('signup/', views.SignUp.as_view() , name='signup'),
    path('cliente/', views.ClienteRegistration.as_view() , name='registroCliente'),
]

homebanking/clientes/models.py
from django.db import models

# Create your models here.

homebanking/clientes/views.py
from django.views.generic import TemplateView

class IndexView(TemplateView):
    template_name = "clientes/index.html"

class AyudaView(TemplateView):
    template_name = "clientes/ayuda.html"

class DivisasView(TemplateView):
    template_name = "clientes/divisas.html"

homebanking/clientes/templates/clientes/ayuda.html
{% extends 'cuentas/base.html' %}
{% load static%}

{% block content %}
<div class="home-content">
    <div class="accordion">
        <h2>Preguntas Frecuentes</h2>
        <div class="accordion-content">
            <div class="header">
                <span class="title">Pregunta 1</span>
                <i class='bx bx-plus'></i>
            </div>
    
            <p class="description">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Natus nobis ut perspiciatis minima quidem nisi, obcaecati, delectus consequatur fuga nostrum iusto ipsam ducimus quibusdam possimus. Maiores non enim numquam voluptatem?
            </p>
        </div>
        <div class="accordion-content">
            <div class="header">
                <span class="title">Pregunta 2</span>
                <i class='bx bx-plus'></i>
            </div>
    
            <p class="description">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Natus nobis ut perspiciatis minima quidem nisi, obcaecati, delectus consequatur fuga nostrum iusto ipsam ducimus quibusdam possimus. Maiores non enim numquam voluptatem?
            </p>
        </div>
        <div class="accordion-content">
            <div class="header">
                <span class="title">Pregunta 3</span>
                <i class='bx bx-plus'></i>
            </div>
    
            <p class="description">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Natus nobis ut perspiciatis minima quidem nisi, obcaecati, delectus consequatur fuga nostrum iusto ipsam ducimus quibusdam possimus. Maiores non enim numquam voluptatem?
            </p>
        </div>
    
        <div class="accordion-content">
            <div class="header">
                <span class="title">Pregunta 4</span>
                <i class='bx bx-plus'></i>
            </div>
    
            <p class="description">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Natus nobis ut perspiciatis minima quidem nisi, obcaecati, delectus consequatur fuga nostrum iusto ipsam ducimus quibusdam possimus. Maiores non enim numquam voluptatem?
            </p>
        </div>
        <div class="accordion-content">
            <div class="header">
                <span class="title">Pregunta 5</span>
                <i class='bx bx-plus'></i>
            </div>
    
            <p class="description">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Natus nobis ut perspiciatis minima quidem nisi, obcaecati, delectus consequatur fuga nostrum iusto ipsam ducimus quibusdam possimus. Maiores non enim numquam voluptatem?
            </p>
        </div>
        <div class="accordion-content">
            <div class="header">
                <span class="title">Pregunta 6</span>
                <i class='bx bx-plus'></i>
            </div>
    
            <p class="description">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Natus nobis ut perspiciatis minima quidem nisi, obcaecati, delectus consequatur fuga nostrum iusto ipsam ducimus quibusdam possimus. Maiores non enim numquam voluptatem?
            </p>
        </div>
    </div>
</div>

<script src="{% static 'clientes/js/ayuda.js'%}"></script>
{% endblock %}

homebanking/clientes/templates/clientes/divisas.html
{% extends 'cuentas/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'clientes/css/divisas.css'  %}">

<div class="home-content">
    <section class="contenedor-divisas">
    <h2>Cotizacion de Divisas</h2>
      <section>
        <table>
          <thead id="head">
          </thead>
          <tbody id="data">
          </tbody>
        </table>
      </section>
    </section>
  <script src="{% static 'clientes/js/divisas.js' %}"></script>

</html>
</div>
{% endblock %}

homebanking/clientes/templates/clientes/home.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
    
</head>
<body>
    {% load static %}

    <link rel="stylesheet" href="{% static 'clientes/css/clientes.css' %}">

    <nav class="sidebar close">
        <header>
            <div class="image-text">
                <span class="image">
                    <img src="{% static 'clientes/images/perfil.jpg' %}" alt="">
                </span>

                <div class="text logo-text">
                    <span class="name">User</span>
                </div>
            </div>

            <i class='bx bx-chevron-right toggle'></i>
        </header>

        <div class="menu-bar">
            <div class="menu">
                <ul class="menu-links">
                    <li class="nav-link">
                        <a href="#">
                            <i class='bx bx-home-alt icon' ></i>
                            <span class="text nav-text">Inicio</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a href="#">
                            <i class='bx bx-user icon'></i>
                            <span class="text nav-text">Perfil</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a href="#">
                            <i class='bx bx-wallet icon'></i>
                            <span class="text nav-text">Fondos</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a href="#">
                            <i class='bx bx-send icon'></i>
                            <span class="text nav-text">Enviar Dinero</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a href="#">
                            <i class='bx bx-money-withdraw icon'></i>
                            <span class="text nav-text">Divisas</span>
                        </a>
                    </li>

                    <li class="nav-link">
                        <a href="#">
                            <i class='bx bx-help-circle icon'></i>
                            <span class="text nav-text">Ayuda</span>
                        </a>
                    </li>

                </ul>
            </div>

            <div class="bottom-content">
                <li class="">
                    <a href="#">
                        <i class='bx bx-log-out icon' ></i>
                        <span class="text nav-text">Cerrar sesión</span>
                    </a>
                </li>

            </div>
        </div>

    </nav>
    {% block content %}
    {% endblock %}

    <script src="{% static 'clientes/js/clientes.js' %}"></script>

</body>
</html>

homebanking/clientes/templates/clientes/index.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="../../static/clientes/css/index.css">

    {% load static %}
    <link rel="stylesheet" href="{% static 'clientes/css/index.css' %}">
    <script src="https://kit.fontawesome.com/a8edf64d36.js" crossorigin="anonymous"></script>

</head>

<body>

    <header>
        <a href="">
            <figure id="figure-logo">
                <img src="{% static 'registration/images/logo_itbank.png' %}" alt="">
            </figure>
        </a>
        <div class="buttons">
            {% if user.is_authenticated %}
            <a href="{% url 'cuentas:cuenta' %}" class="btn btn-outline-primary">Ver Cuenta</a>
            <a href="{% url 'logout' %}" class="btn btn-primary">Cerrar Sesión</a>
            {%else%}
            <a href="{% url 'login' %}" class="btn btn-outline-primary">Iniciar sesión</a>
            <a href="{% url 'registration:signup' %}" class="btn btn-primary">Abrir cuenta</a>
            {% endif %}
        </div>
    </header>
    <main>
        <section class="banner">
            <h1>Bienvenido/a a Itbank!</h1>
        </section>
        <section class="divisas">
            <div class="divisas__card" id="divisas">
                <div class="card">
                    <div class="card-body">
                        <div class="divisa">
                            <h3>Dolar Oficial</h3>
                        </div>
                        <div class="compra-venta">
                            <p>Compra:<span></span></p>
                            <p>Venta:<span></span></p>
                        </div>
                        <div class="variacion">
                            <p>Variacion:<span></span></p>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <div class="divisa">
                            <h3>Dolar Blue</h3>
                        </div>
                        <div class="compra-venta">
                            <p>Compra:<span></span></p>
                            <p>Venta:<span></span></p>
                        </div>
                        <div class="variacion">
                            <p>Variacion:<span></span></p>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <div class="divisa">
                            <h3>Dolar Bolsa</h3>
                        </div>
                        <div class="compra-venta">
                            <p>Compra:<span></span></p>
                            <p>Venta:<span></span></p>
                        </div>
                        <div class="variacion">
                            <p>Variacion:<span></span></p>
                        </div>
                    </div>
                </div>
                <div class="mas">
                    <a href="{% url 'clientes:divisas' %}" title="Ver más divisas"><i class="bi bi-plus-circle"></i>
                        <small>Ver más</small>
                    </a>
                </div>
            </div>
        </section>
        <section class="servicios">
            <div>
                <span><i class="bi bi-arrow-left-right"></i></span>
                <h4>Transferencias</h4>
                <p>Enviá y recibí plata desde cualquier cuenta bancaria y/o virtual, gratis y en el acto.</p>
                <a href="">Ver más</a>
            </div>
            <div>
                <span><i class="bi bi-credit-card-2-front"></i></span>
                <h4>Tarjetas</h4>
                <p>Aprovechá tu tarjeta Itbanky comprá en cualquier comercio o página web del mundo.</p>
                <a href="">Ver más</a>
            </div>
            <div>
                <span><i class="bi bi-cash-stack"></i></span>
                <h4>Prestamos</h4>
                <p>Para lo que necesites, de la forma más fácil, rápida y transparente.</p>
                <a href="">ver más</a>
            </div>
        </section>
        <section id="ayuda">
            <h4>Atención 100% online</h4>
            <a href="{% url 'clientes:ayuda' %}" class="btn btn-primary">¿En que podemos ayudarte?</a>
            <p>Línea para Clientes: 0800-000-0000</p>
        </section>
    </main>
    <footer>
        <div>
            <p>© 2022 Banco Itbank Argentina. Todos los derechos reservados.</p>
        </div>
        <div>
            <a href=""><i class="bi bi-linkedin"></i></a>
            <a href=""><i class="bi bi-twitter"></i></a>
            <a href=""><i class="bi bi-facebook"></i></a>
            <a href=""><i class="bi bi-instagram"></i></a>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
        crossorigin="anonymous"></script>
    <script src="{% static 'clientes/js/dolar.js' %}"></script>
</body>

</html>